version: '3.8'

services:
  worker_problema:
    build: .
    container_name: worker_problema
    command: python interfaces/workers/problema_no_equipamento.py
    restart: always
    environment:
      - HEADLESS=true

  worker_temporarios:
    build: .
    container_name: worker_temporarios
    command: python interfaces/workers/temporarios.py
    restart: always
    environment:
      - HEADLESS=true